tasks:
  - name: Setup Neovim + LazyVim
    init: |
      # Install Neovim 0.10.0 if not already installed
      if ! command -v nvim >/dev/null || [[ "$(nvim --version | head -n1)" != *"v0.10.0"* ]]; then
        echo "Installing Neovim 0.10.0..."
        curl -LO https://github.com/neovim/neovim/releases/download/v0.10.0/nvim-linux64.tar.gz
        tar -xvzf nvim-linux64.tar.gz
        sudo mv nvim-linux64 /opt/nvim
        sudo ln -sf /opt/nvim/bin/nvim /usr/local/bin/nvim
      else
        echo "Neovim 0.10.0 already installed."
      fi

      # Install LazyVim if not already present
      if [ ! -d "$HOME/.config/nvim" ]; then
        echo "Installing LazyVim..."
        git clone https://github.com/LazyVim/starter ~/.config/nvim
        rm -rf ~/.config/nvim/.git
      else
        echo "LazyVim is already installed."
      fi

    command: nvim
