tasks:
  - name: Setup Neovim + LazyVim
    init: |
    
      # Install Neovim 0.10.0
      curl -LO https://github.com/neovim/neovim/releases/download/v0.10.0/nvim-linux64.tar.gz
      tar -xvzf nvim-linux64.tar.gz
      sudo mv nvim-linux64 /opt/nvim
      sudo ln -sf /opt/nvim/bin/nvim /usr/local/bin/nvim

      # Clone LazyVim config
      git clone https://github.com/LazyVim/starter ~/.config/nvim
      rm -rf ~/.config/nvim/.git

    command: nvim
